#!/usr/bin/env bash
# One-time setup. Run from the repository root:   bash setup.sh
#
# Creates the virtualenv, installs the separation backend, generates an access
# key, and pre-downloads the model so the first upload is not also a 300 MB
# download. Re-running is safe: an existing .env keeps its key.

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$here"

fail() { printf '\n[setup] %s\n' "$1" >&2; exit 1; }
note() { printf '[setup] %s\n' "$1"; }

# ---- prerequisites -------------------------------------------------------

command -v python3 >/dev/null 2>&1 || fail "python3 is not installed."

python3 - <<'PY' || fail "Python 3.10 or newer is required (audio-separator needs it)."
import sys
raise SystemExit(0 if sys.version_info >= (3, 10) else 1)
PY

for tool in ffmpeg ffprobe; do
  command -v "$tool" >/dev/null 2>&1 || fail "$tool is not installed. Run: sudo apt install -y ffmpeg"
done

note "python3 $(python3 -c 'import sys; print("%d.%d.%d" % sys.version_info[:3])'), $(ffmpeg -version | head -1 | cut -d' ' -f1-3)"

# ---- virtualenv ----------------------------------------------------------

if [ ! -d .venv ]; then
  note "creating .venv"
  python3 -m venv .venv || fail "could not create the virtualenv. Run: sudo apt install -y python3-venv"
fi

note "installing audio-separator (this downloads a few hundred MB the first time)"
./.venv/bin/pip install --upgrade pip >/dev/null
./.venv/bin/pip install "audio-separator[cpu]" || fail "the audio-separator install failed; the output above says why."

# ---- configuration -------------------------------------------------------

if [ ! -f .env ]; then
  key="$(python3 -c 'import secrets; print(secrets.token_urlsafe(24))')"
  cat > .env <<EOF
# Generated by setup.sh. Everything here is read at startup.
STEM_ACCESS_KEY=$key
STEM_HOST=127.0.0.1
STEM_PORT=8080
STEM_MAX_UPLOAD_MB=100
STEM_MAX_DURATION_S=600
STEM_JOB_TTL_HOURS=24
STEM_MODEL=htdemucs.yaml
STEM_WORKERS=1
EOF
  chmod 600 .env
  note "wrote .env with a new access key"
else
  note ".env already exists; leaving it alone"
fi

# ---- model ---------------------------------------------------------------

set -a
# shellcheck disable=SC1091
. ./.env
set +a
model="${STEM_MODEL:-htdemucs.yaml}"
model_dir="${STEM_MODEL_DIR:-$here/data/models}"
mkdir -p "$model_dir"

note "fetching the $model weights into $model_dir"
./.venv/bin/audio-separator --download_model_only -m "$model" --model_file_dir "$model_dir" \
  || fail "the model download failed; check network access from this machine."

# ---- verify --------------------------------------------------------------

if PATH="$here/.venv/bin:$PATH" PYTHONPATH="$here/server" \
   ./.venv/bin/python -m stemapp --check; then
  note "checks passed"
else
  fail "the tool check failed; see above."
fi

printf '\n'
note "done. Start it with:   bash run.sh"
note "your access key is in .env"
